import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Swap from '../components/Swap'

const Exchange: NextPage = () => {
  return (
    <div className={`min-h-[100vh] md:h-[100vh] font-plex bg-[#0b0e11]`}>
      <Head>
        <title>GelatoSwap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <Navbar />
      <Swap />
    </div>
  )
}

export default Exchange


