import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Landing from '../components/Landing'




function Homepage({ properties, response }: any) {
  console.log(properties)
  console.log(response)

  return (
    <div className={`h-[100vh] font-plex bg-[#0b0e11]`}>
      <Head>
        <title>GelatoSwap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <Navbar />
      <Landing props={properties} response = {response}/>
    </div>
  )
}

export default Homepage


export async function getStaticProps() {


  let requestOptions: any = {
    method: 'GET',
    redirect: 'follow'
  };
  
  let response = await fetch("http://api.coincap.io/v2/assets", requestOptions)
    let _response = await response.json()
    
  return {
    props: {
      response: _response.data,
      properties: [
        {
          symbol: "btc/usdt",
          price: "623522"
        },
        {
          symbol: "eth/usdt",
          price: "62352"
        },
        {
          symbol: "bnb/usdt",
          price: "6235"
        },
        {
          symbol: "dot/usdt",
          price: "62"
        },
        {
          symbol: "ada/usdt",
          price: "63"
        },
        {
          symbol: "xrp/usdt",
          price: "6"
        },
      ]
    }
  }
}